### PR TITLE
Add self.hostname

### PR DESCRIPTION
**Pull request by bouwew**

### CODE REVIEW

**Comment by CoMPaTech** [comment]
Does this work across v2/v3?

**Comment by bouwew** [comment]
I think it should, due to all the added checks. Also, no zeroconf discovery for P1 v2 so safe to use the gateway_id.
And we also need code as in https://github.com/plugwise/plugwise-beta/commit/b693577065995044547f3be673628ef4470a99bb

But, there's no gateway_id assigned for the P1 v2? See our private topic on Discord.

**Comment by bouwew** [comment]
Confirmed by Martin, the Smile P1 v2 does not support zeroconf discovery.
So, add via Integrations --> + --> enter IP and password.

**Comment by CoMPaTech** [comment]
Looking good

**Pull request merged**
